logging:
  level:
    com.guardjo.ticketmanager: debug
    org.hibernate.type.descriptor.sql: debug

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ticket-manager"
    username: manager
    password: manager1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      encoding: UTF-8